language: clojure
env:
  global:
    - secure: "XbXWv472/CIOk5ydmYPe7XVLcNmjrPqvwJBeYS9BqR60MPzSOxmu6YXJ0tIE\n4K0ldMy9vcqONojcBNcd7JzS84kydtStMSdW235XJ0s5ylxGUMVCtupm53B4\n60anwP4j5gzr/0ULVEAbcmBAL2vGuI+ofvA8zi/AoBljK67Rkdc="
script:
    - lein test
    - ./bin/push.sh
